services:

  infra:
    path: infra
    config: serverless.ts
    params:
      region: eu-west-1
  api:
    path: api
    config: serverless.ts
    dependsOn:
      - infra
    params:
      region: eu-west-1
      # cognito
      userPoolName: ${infra.userPoolName}
      userPoolId: ${infra.userPoolId}
      userPoolArn: ${infra.userPoolArn}
      appClientId: ${infra.appClientId}
      # dynamodb
      todosTableName: ${infra.todosTableName}
      todosTableArn: ${infra.todosTableArn}
      usersTableName: ${infra.usersTableName}
      usersTableArn: ${infra.usersTableArn}
      usersTableStreamArn: ${infra.usersTableStreamArn}
