name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm-version: [8.3.1]
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        region: [eu-west-1]
    steps:
      - name: Deploy to AWS
        run: pnpm run deploy
        env:
          # AWS VARIABLES
          AWS_REGION: ${{ matrix.region }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # APP VARIABLES
          ACCESS_TOKEN_VALIDITY: 24
          ID_TOKEN_VALIDITY: 24
          REFRESH_TOKEN_VALIDITY: 72

