name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: 18.x
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Show variables
        run: |
          echo "ACCESS_TOKEN_VALIDITY : ${{ env.ACCESS_TOKEN_VALIDITY }}"
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i

#      - name: Run lint
#        run: pnpm run lint

      - name: Run build
        run: pnpm run build

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    environment:
      name: Development
      url: https://xxxxxxxx.execute-api.eu-west-1.amazonaws.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i

      - name: Deploy to AWS
        run: pnpm run deploy
        env:
          # AWS CREDENTIALS VARIABLES
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # *********** INFRA VARIABLES ***********
          # Cognito user pool token validity config
          # ACCESS_TOKEN_VALIDITY in hours
          ACCESS_TOKEN_VALIDITY: 24
          # ID_TOKEN_VALIDITY in hours
          ID_TOKEN_VALIDITY: 24
          # REFRESH_TOKEN_VALIDITY in days
          REFRESH_TOKEN_VALIDITY: 30

